### PR TITLE
feat(front-end): support init front end

### PR DESCRIPTION
**Pull request by lwaekfjlk**
Closes # 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

### CODE REVIEW

**Review by lwaekfjlk — COMMENTED** [review]
@YuanhuanO do we need all these components?

**Comment by lwaekfjlk** [comment]
I saw there is CarolZhang's name in the changes. Is that part necessary?

**Comment by lwaekfjlk** [comment]
@YuanhuanO I also saw a .DS_store in the code. I think we should delete that.

**Comment by lwaekfjlk** [comment]
@YuanhuanO my suggestion is that put the whole frontend in one folder that is at the same level with the src. https://github.com/OpenDevin/OpenDevin/tree/main check their frontend folder position and structure.

**Comment by YuanhuanO** [comment]
> @YuanhuanO do we need all these components?

which part are you referring to?

**Comment by lwaekfjlk** [comment]
@YuanhuanO I change the file name, does it make sense?

**Comment by lwaekfjlk** [comment]
Feel free to merge

**Comment by lwaekfjlk** [comment]
since all the CI has passed, I will merge this PR.

**Pull request merged**
