### PR TITLE
fix(frontend): npm localhost3000 not found

### PR DESCRIPTION
**Pull request by YuanhuanO**
Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [x] Ready for code review

### CODE REVIEW

**Review by lwaekfjlk — COMMENTED** [review]
let me test on this branch before mering

**Comment by lwaekfjlk** [comment]
@YuanhuanO 

```
(base) haofeiyu@haofeis-mbp gpu-bartender % npm start
npm error code ENOENT
npm error syscall open
npm error path /Users/haofeiyu/Desktop/gpu-bartender/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/haofeiyu/Desktop/gpu-bartender/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent

npm error A complete log of this run can be found in: /Users/haofeiyu/.npm/_logs/2024-08-01T02_16_07_918Z-debug-0.log
```

**Comment by lwaekfjlk** [comment]
how to solve this error?

**Comment by lwaekfjlk** [comment]
I think it is due to the removal of package.json?

**Review by lwaekfjlk — CHANGES_REQUESTED** [review]
I failed to run npm when running `npm start` in the root folder. The error is included in the conversation. Looks like it is related to a path error.

**Comment by YuanhuanO** [comment]
> let me test on this branch before mering



> I failed to run npm when running `npm start` in the root folder. The error is included in the conversation. Looks like it is related to a path error.

Please try to run under the frontend file because of the structure changes

**Comment by YuanhuanO** [comment]
> > let me test on this branch before mering
> 
> > I failed to run npm when running `npm start` in the root folder. The error is included in the conversation. Looks like it is related to a path error.
> 
> Please try to run under the frontend file because of the structure changes

README.md was also modified as:
1. Clone the repository:

    ```bash
    git clone git@github.com:lwaekfjlk/gpu-bartender.git
    ```

2. Navigate to the root directory:

    ```bash
    cd frontend
    ```

3. Install dependencies:

    ```bash
    npm install
    ```

4. Build the project:

    ```bash
    npm run build
    ```

5. Start the application:

    ```bash
    cd gpu-bartender
    npm start
    ```

**Comment by lwaekfjlk** [comment]
yeah, but the npm start is still at the root folder?

**Comment by YuanhuanO** [comment]
> yeah, but the npm start is still at the root folder?

yes

**Pull request merged**
